config/routes.rb
Rails.application.routes.draw do
  resources :libraries
  resources :archives
  resources :profiles
  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "mainpage#mainpage"
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
	validates :user_id, presence:true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = current_user.build_profile
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create

    @profile = current_user.build_profile(profile_params)
    Library.create(user_id: current_user.id)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:user_id, :description)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :description %>
  </div>
  
  <br>

  <div class="actions">
    <input class="btn btn-warning" type="submit" value="Submit">
  </div>
<% end %>

app/views/profiles/edit.html.erb
<% if user_signed_in? %> 
	<h1>Editing Profile</h1>

	<% if current_user.id == @profile.user_id %>
		<%= render 'form', profile: @profile %>
	<% else %>
	<strong>Não é possível editar um perfil que não é seu.</strong>
	<% end %>
	<br>
	<%= link_to 'Show', @profile %>
<% else %>
	<strong>You need to login to see this page!</strong>
	<br>
	<%= link_to('Login', new_user_session_path) %>
<% end %>

app/views/profiles/index.html.erb
<% if user_signed_in? %> 
  <p id="notice"><%= notice %></p>

  <h1>Profiles</h1>

  <table>
    <thead>
      <tr>
        <th>User</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @profiles.each do |profile| %>
        <tr>
          <td><%= profile.user_id %></td>
          <td><%= profile.description %></td>
          <td><%= link_to 'Show', profile %></td>
          <% if current_user.id == profile.user_id %>
            <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
            <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Profile', new_profile_path %>
<% else %>
  <strong>You need to login to see this page!</strong>
  <br>
  <%= link_to('Login', new_user_session_path) %>
<% end %>

app/views/profiles/new.html.erb
<% if user_signed_in? %> 
	
	<nav class="navbar navbar-white bg-white">
  <a class="navbar-brand">
    <%= image_tag "SharequillLogoBar", :size => "211x70"%>
  </a>
</nav>
	<br>
	<br>
	<strong>Add your description:</strong>
	<br>
	<br>
	<%= render 'form', profile: @profile %>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>

	<button type="button" class="btn btn-warning">
    	<%= link_to 'Back', root_path, :style=>'color:#FFFFFF;', :class => "css_class" %>		
    </button>

<% else %>
  <strong>You need to login to see this page!</strong>
  <br>
  <%= link_to('Login', new_user_session_path) %>
<% end %>

app/views/profiles/show.html.erb
<% if user_signed_in? %> 
	<p id="notice"><%= notice %></p>

	<nav class="navbar fixed-top navbar-white bg-white">
  <a class="navbar-brand">
    <%= image_tag "SharequillLogoBar", :size => "211x70"%><button type="button" class="btn btn-warning">
    <%= link_to('Logout', destroy_user_session_path, method: :delete, :style=>'color:#FFFFFF;', :class => "css_class" ) %></button> 
  </a>
</nav>
<br>
<br>
<br>
	<nav class="navbar navbar-warning bg-warning">
		<button type="button" class="btn btn-warning">
			<%= link_to'Main Page', root_path,{:style=>'color:#FFFFFF;', :class => "css_class"} %> 
		</button>
		<br>
		<% if current_user.id == @profile.user_id %>


		<button type="button" class="btn btn-warning">
			<%= link_to 'Edit Profile', edit_profile_path(@profile),{:style=>'color:#FFFFFF;', :class => "css_class"} %>
		</button>

		<button type="button" class="btn btn-warning">
			<%= link_to "Edit User", edit_user_registration_path,{:style=>'color:#FFFFFF;', :class => "css_class"}%>
		</button>
			<% if current_user.library == nil %>
				<%= link_to'Create Library', new_library_path,{:style=>'color:#FFFFFF;', :class => "css_class"} %>
			<% else %>
		<button type="button" class="btn btn-warning">
				<%= link_to'View Your Library', current_user.library,{:style=>'color:#FFFFFF;', :class => "css_class"} %>
		</button>
			<% end %>
		<% else %>
		<button type="button" class="btn btn-warning-dark">
			<%= link_to'View Library', library_path(@profile.user_id),{:style=>'color:#FFFFFF;', :class => "css_class"}%>
		</button>
		<% end %>
	</nav>

	<br>

	<p>
	  <strong><%= User.find(@profile.user_id).firstname + " " + User.find(@profile.user_id).lastname %></strong>
	</p>

	<p>
	  <strong><%= User.find(@profile.user_id).username%></strong>
	</p>

	<p>
	  <strong>Description:</strong>
	  <%= @profile.description %>
	</p>

	<% User.find(@profile.user_id).posts.each do |post| %>
	<nav class="navbar navbar-light bg-light">
  		<span class="navbar-text">
			<%= link_to(post.post, post_path(post)) %>
			<br>
			Created at: 
			<%= post.created_at%>
	  	</span>
	</nav>
	<br>

	<%end%>

<% else %>
  <strong>You need to login to see this page!</strong>
  <br>
  <%= link_to('Login', new_user_session_path) %>
<% end %>