config/routes.rb
Rails.application.routes.draw do
  resources :libraries
  resources :archives
  resources :profiles
  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "mainpage#mainpage"
end

app/models/library.rb
class Library < ApplicationRecord
	belongs_to :user
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: [:show, :edit, :update, :destroy]

  # GET /libraries
  # GET /libraries.json
  def index
    @libraries = Library.all
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
  end

  # GET /libraries/new
  def new
    @library = current_user.build_library
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = current_user.build_library(library_params)

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Library was successfully created.' }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1
  # PATCH/PUT /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to @library, notice: 'Library was successfully updated.' }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library.destroy
    respond_to do |format|
      format.html { redirect_to libraries_url, notice: 'Library was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def library_params
      params.fetch(:library, {})
    end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_with(model: library, local: true) do |form| %>
  <% if library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
      <% library.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/libraries/edit.html.erb
<% if user_signed_in? %> 
	<h1>Editing Library</h1>

	<%= render 'form', library: @library %>

	<%= link_to 'Show', @library %> |
	<%= link_to 'Back', libraries_path %>
<% else %>
  <strong>You need to login to see this page!</strong>
  <br>
  <%= link_to('Login', new_user_session_path) %>
<% end %>

app/views/libraries/index.html.erb
<% if user_signed_in? %> 
  <% if current_user == current_user %>
    <strong>Acess denied! You cant see this page!</strong>
  <% else %>
    <p id="notice"><%= notice %></p>

    <h1>Libraries</h1>

    <table>
      <thead>
        <tr>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @libraries.each do |library| %>
          <tr>
            <td><%= link_to 'Show', library %></td>
            <td><%= link_to 'Edit', edit_library_path(library) %></td>
            <td><%= link_to 'Destroy', library, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Library', new_library_path %>
  <% end %>
<% else %>
  <strong>You need to login to see this page!</strong>
  <br>
  <%= link_to('Login', new_user_session_path) %>
<% end %>

app/views/libraries/new.html.erb
<% if user_signed_in? %> 
	<h1>New Library</h1>

	<%= render 'form', library: @library %>

<% else %>
	<strong>You need to login to see this page!</strong>
	<br>
	<%= link_to('Login', new_user_session_path) %>
<% end %>

app/views/libraries/show.html.erb
<% if user_signed_in? %> 

	<p id="notice"><%= notice %></p>

	<nav class="navbar fixed-top navbar-white bg-white">
  		<a class="navbar-brand">
    		<%= image_tag "SharequillLogoBar", :size => "211x70"%>
		</a>
	</nav>
	<br>
	<br>
	<br>

<nav class="navbar navbar-warning bg-warning">
	<% if current_user.id == @library.user_id %>
	<button type="button" class="btn btn-warning">
		<%= link_to 'New Archive', new_archive_path,{:style=>'color:#FFFFFF;', :class => "css_class"} %>
	</button>
		<br>
	<% end %>
	<button type="button" class="btn btn-warning">
		<%= link_to 'Back', profile_path(@library.user_id),{:style=>'color:#FFFFFF;', :class => "css_class"} %>
	</button>
	<br>
</nav>
	<br>
	<br>
	<p>
	  <strong><%= User.find(@library.user_id).firstname + " " + User.find(@library.user_id).lastname %> 's library</strong>
	</p>

	<br>


	<% User.find(@library.user_id).archives.each do |archive| %>
		<nav class="navbar navbar-light bg-light">
  			<span class="navbar-text">
				<%= link_to(archive.title, archive_path(archive)) %>
	 		</span>
		</nav>
		<br>
	<%end%>
<% else %>
	<strong>You need to login to see this page!</strong>
	<br>
	<%= link_to('Login', new_user_session_path) %>
<% end %>