config/routes.rb
Rails.application.routes.draw do
  resources :libraries
  resources :archives
  resources :profiles
  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "mainpage#mainpage"
end

app/models/archive.rb
class Archive < ApplicationRecord
	belongs_to :user
	validates :title, presence:true
	validates :text, presence:true
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  before_action :set_archive, only: [:show, :edit, :update, :destroy]

  # GET /archives
  # GET /archives.json
  def index
    @archives = Archive.all
  end

  # GET /archives/1
  # GET /archives/1.json
  def show
  end

  # GET /archives/new
  def new
    @archive = current_user.archives.build
  end

  # GET /archives/1/edit
  def edit
  end

  # POST /archives
  # POST /archives.json
  def create
    @archive = current_user.archives.build(archive_params)
    Post.create(post: "Check my new archive: '" + @archive.title + "' at my library.", user_id: current_user.id)

    respond_to do |format|
      if @archive.save
        format.html { redirect_to @archive, notice: 'Archive was successfully created.' }
        format.json { render :show, status: :created, location: @archive }
      else
        format.html { render :new }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /archives/1
  # PATCH/PUT /archives/1.json
  def update
    respond_to do |format|
      if @archive.update(archive_params)
        format.html { redirect_to @archive, notice: 'Archive was successfully updated.' }
        format.json { render :show, status: :ok, location: @archive }
      else
        format.html { render :edit }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /archives/1
  # DELETE /archives/1.json
  def destroy
    @archive.destroy
    respond_to do |format|
      format.html { redirect_to archives_url, notice: 'Archive was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_archive
      @archive = Archive.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def archive_params
      params.require(:archive).permit(:title, :text)
    end
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/views/archives/_form.html.erb
<%= form_with(model: archive, local: true) do |form| %>
  <% if archive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(archive.errors.count, "error") %> prohibited this archive from being saved:</h2>

      <ul>
      <% archive.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <br>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, :rows=>10, style:'width:100%;'%>
  </div>

  <br>

  <div class="actions">
    <input class="btn btn-warning" type="submit" value="Submit"></div>

  <br>
  
<% end %>

app/views/archives/edit.html.erb
<% if user_signed_in? %> 
	<h1>Editing Archive</h1>

	<%= render 'form', archive: @archive %>

	<%= link_to 'Show', @archive %> |
	<%= link_to 'Back', library_path(@archive.user_id) %>
<% else %>
	<strong>You need to login to see this page!</strong>
	<br>
	<%= link_to('Login', new_user_session_path) %>
<% end %>

app/views/archives/index.html.erb
<% if user_signed_in? %> 
  <% if current_user == current_user %>
    <strong>Acess denied! You cant see this page!</strong>
  <% else %>
    <p id="notice"><%= notice %></p>

    <h1>Archives</h1>

    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Text</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @archives.each do |archive| %>
          <tr>
            <td><%= archive.title %></td>
            <td><%= archive.text %></td>
            <td><%= link_to 'Show', archive %></td>
            <td><%= link_to 'Edit', edit_archive_path(archive) %></td>
            <td><%= link_to 'Destroy', archive, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Archive', new_archive_path %>
  <% end %>

<% else %>
  <strong>You need to login to see this page!</strong>
  <br>
  <%= link_to('Login', new_user_session_path) %>
<% end %>

app/views/archives/new.html.erb
<% if user_signed_in? %> 
	
	 <nav class="navbar fixed-top navbar-white bg-white">
  		<a class="navbar-brand">
    		<%= image_tag "SharequillLogoBar", :size => "211x70"%><button type="button" class="btn btn-warning">
    		<%= link_to('Logout', destroy_user_session_path, method: :delete, :style=>'color:#FFFFFF;', :class => "css_class" ) %></button> 
  		</a>
	</nav>
	
	<br>
	<br>
	<br>
	<br>
		<%= render 'form', archive: @archive %>
		<button type="button" class="btn btn-warning">
			<%= link_to 'Back', profile_path(current_user.id), :style=>'color:#000000;', :class => "css_class" %>
		</button>
<% else %>
	<strong>You need to login to see this page!</strong>
	<br>
	<%= link_to('Login', new_user_session_path) %>
<% end %>

app/views/archives/show.html.erb
<% if user_signed_in? %> 

	<nav class="navbar navbar-white bg-white">
  <a class="navbar-brand">
    <%= image_tag "SharequillLogoBar", :size => "211x70"%>
  </a>
</nav>


	<p id="notice"><%= notice %></p>

	<h1>
		<p class="text-center">
	  		<strong><%= @archive.title %></strong>
		</p>
	</h1>
	<br>
	<p class="text-justify">
	  <%= simple_format @archive.text %>
	</p>

<nav class="navbar navbar-white bg-white">
	<% if current_user.id == @archive.user_id %>
		<button type="button" class="btn btn-warning">
			<%= link_to 'Edit', edit_archive_path(@archive),{:style=>'color:#FFFFFF;', :class => "css_class"} %>
		</button>
		<br>
		<br>
	<% end %>
	<button type="button" class="btn btn-warning">
		<%= link_to 'Back',  library_path(@archive.user_id),{:style=>'color:#FFFFFF;', :class => "css_class"} %>
	</button>
	<br>
	<br>
<% else %>
	<strong>You need to login to see this page!</strong>
	<br>
	<%= link_to('Login', new_user_session_path) %>
<% end %>

</nav>