config/routes.rb
Rails.application.routes.draw do
  resources :libraries
  resources :archives
  resources :profiles
  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "mainpage#mainpage"
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	validates :post, presence:true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:post)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :post %>
  </div>

  <br>

  <div class="actions">
    <input class="btn btn-warning" type="submit" value="Submit">
  </div>
<% end %>

app/views/posts/edit.html.erb
<% if user_signed_in? %> 
	
	  <nav class="navbar fixed-top navbar-white bg-white">
  		<a class="navbar-brand">
    		<%= image_tag "SharequillLogoBar", :size => "211x70"%><button type="button" class="btn btn-warning">
    		<%= link_to('Logout', destroy_user_session_path, method: :delete, :style=>'color:#FFFFFF;', :class => "css_class" ) %></button> 
  		</a>
	</nav>
	<br>
	<br>
	<br>
	<br>

	<%= render 'form', post: @post %>

	<br>

	<button type="button" class="btn btn-warning">
		<%= link_to 'Back', posts_path , :style=>'color:#000000;', :class => "css_class"%>
	</button>

<% else %>
	<strong>You need to login to see this page!</strong>
	<br>
	<%= link_to('Login', new_user_session_path) %>
<% end %>

app/views/posts/index.html.erb
<% if user_signed_in? %> 
  <p id="notice"><%= notice %></p>

  <nav class="navbar fixed-top navbar-white bg-white">
  <a class="navbar-brand">
    <%= image_tag "SharequillLogoBar", :size => "211x70"%><button type="button" class="btn btn-warning">
    <%= link_to('Logout', destroy_user_session_path, method: :delete, :style=>'color:#FFFFFF;', :class => "css_class" ) %></button> 
  </a>
</nav>
    <br>
      <br>
  <br>
  <br>


  <button type="button" class="btn btn-warning">
    <%= link_to 'Main page', root_path, :style=>'color:#FFFFFF;', :class => "css_class"%>
  </button>

  <br>

  <br>

    <button type="button" class="btn btn-warning">
    <%= link_to 'New Post', new_post_path,:style=>'color:#FFFFFF;', :class => "css_class"%>
    </button>

    <br>
    <br>

    <tbody>
      <% @posts.each do |post| %>
        <nav class="navbar navbar-light bg-light">
          <span class="navbar-text">
            @<%=link_to(User.find(post.user_id).username, profile_path(post.user_id),:style=>'color:#EB6123;', :class => "css_class")%>
            <br>
            <%= post.post %>
            <br>
            <% if current_user.id == post.user_id %>
             | <%= link_to 'Edit', edit_post_path(post),:style=>'color:#EB6123;', :class => "css_class" %> |
              <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' },:style=>'color:#EB6123;', :class => "css_class"%> |
              <br>
            <% end %>
          </span>
        </nav>
        <br>
        <br>
      <% end %>
    </tbody>


  <br>

<% else %>
<strong>You need to login to see this page!</strong>
<br>
<%= link_to('Login', new_user_session_path) %>
<% end %>

app/views/posts/new.html.erb
<% if user_signed_in? %> 
	
  <nav class="navbar fixed-top navbar-white bg-white">
  <a class="navbar-brand">
    <%= image_tag "SharequillLogoBar", :size => "211x70"%><button type="button" class="btn btn-warning">
    <%= link_to('Logout', destroy_user_session_path, method: :delete, :style=>'color:#FFFFFF;', :class => "css_class" ) %></button> 
  </a>
</nav>
	<br>
	<br>
	<br>
	<br>
	<%= render 'form', post: @post %>
	<br>

	<button type="button" class="btn btn-warning">
		<%= link_to 'Back', posts_path , :style=>'color:#000000;', :class => "css_class"%>
	</button> 


<% else %>
	<strong>You need to login to see this page!</strong>
	<br>
	<%= link_to('Login', new_user_session_path) %>
<% end %>

app/views/posts/show.html.erb
<% if user_signed_in? %> 
	<p id="notice"><%= notice %></p>

	  <strong><%=User.find(@post.user_id).username%>:</strong>
	  <br>
	  <%= @post.post %>
	<br>
	<% if current_user.id == @post.user_id %>
		<%= link_to 'Edit', edit_post_path(@post) %>   |
		<td><%= link_to 'Delete', post_path, method: :delete, data: { confirm: 'Are you sure?' }%></td>
	<% end %>
	<br>
	<br>
	<%= link_to 'Back to Feed', posts_path %>
	<br>
	<%= link_to 'Back to Profile', profile_path(@post.user_id) %>
<% else %>
	<strong>You need to login to see this page!</strong>
	<br>
	<%= link_to('Login', new_user_session_path) %>
<% end %>